# Generated by Django 5.1.6 on 2025-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="use_on",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
