# Generated by Django 5.1.6 on 2025-02-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("name", models.CharField(max_length=10)),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("completed", "completed"),
                            ("expired", "expired"),
                            ("canceled", "canceled"),
                            ("mismatch", "mismatch"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("merchant_id", models.CharField(max_length=255)),
                ("goods_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("buyer_name", models.CharField(max_length=255)),
                ("buyer_tel", models.CharField(max_length=20)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("moid", models.CharField(max_length=255)),
                ("return_url", models.URLField()),
                ("edi_date", models.CharField(blank=True, max_length=20, null=True)),
                ("hash_str", models.CharField(blank=True, max_length=255, null=True)),
                ("result_code", models.CharField(blank=True, max_length=4, null=True)),
                ("result_msg", models.CharField(blank=True, max_length=255, null=True)),
                ("tid", models.CharField(blank=True, max_length=255, null=True)),
                ("app_no", models.CharField(blank=True, max_length=255, null=True)),
                ("card_no", models.CharField(blank=True, max_length=255, null=True)),
                ("pay_method", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("discount_price", models.IntegerField()),
                ("img_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("count", models.IntegerField(default=1)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="payment.products")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("amount", models.IntegerField()),
                ("method", models.CharField(choices=[("bank_transfer", "bank_transfer"), ("port_one", "port_one")])),
                (
                    "status",
                    models.CharField(choices=[("pending", "pending"), ("complete", "complete"), ("failed", "failed")]),
                ),
                (
                    "bank_transfer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="payment.banktransfer"),
                ),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="payment.order")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
