# Generated by Django 5.1.6 on 2025-02-20 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankpay", "0001_initial"),
        ("payment", "0001_initial"),
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("imp_uid", models.CharField(max_length=50, unique=True, verbose_name="포트원 결제 고유번호")),
                ("merchant_uid", models.CharField(max_length=50, unique=True, verbose_name="가맹점 주문번호")),
                ("amount", models.PositiveIntegerField(verbose_name="결제 금액")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "결제 대기"),
                            ("paid", "결제 완료"),
                            ("failed", "결제 실패"),
                            ("cancelled", "결제 취소"),
                            ("refunded", "환불 완료"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="결제 상태",
                    ),
                ),
                ("buyer_email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="구매자 이메일")),
                ("buyer_name", models.CharField(blank=True, max_length=100, null=True, verbose_name="구매자 이름")),
                ("buyer_tel", models.CharField(blank=True, max_length=20, null=True, verbose_name="구매자 전화번호")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="Order",
            new_name="Orders",
        ),
        migrations.AlterField(
            model_name="payments",
            name="bank_transfer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bankpay.banktransfer"),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
        migrations.AlterField(
            model_name="orders",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.product"),
        ),
        migrations.DeleteModel(
            name="BankTransfer",
        ),
    ]
