# Generated by Django 5.1.6 on 2025-02-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("payment", "0003_order_payment_refund_remove_orders_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="order.order"
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
