# Generated by Django 5.1.6 on 2025-02-13 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0003_category_notice_category"),
        ("notification", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notiuser",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="notiuser",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notice.category",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notiuser",
            name="read_users",
            field=models.ManyToManyField(related_name="readusers", to=settings.AUTH_USER_MODEL),
        ),
    ]
