# Generated by Django 5.1.6 on 2025-02-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpers", "__first__"),
        ("notification", "0003_remove_notiuser_is_read_remove_notiuser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="helpers.category",
            ),
        ),
    ]
