# Generated by Django 5.1.6 on 2025-02-14 02:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_notification_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notiuser",
            name="read_users",
        ),
        migrations.AddField(
            model_name="notiuser",
            name="read_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
