# Generated by Django 5.1.6 on 2025-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankpay", "0002_bankorders_bankpayments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransfer",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
