# Generated by Django 5.1.6 on 2025-02-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_initial"),
        ("tarot", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="taro_chat_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="tarot.tarochatrooms",
            ),
        ),
    ]
