# Generated by Django 5.1.6 on 2025-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("img_url", models.URLField(blank=True, max_length=500, null=True)),
                ("order", models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
