# Generated by Django 5.1.6 on 2025-02-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpers", "__first__"),
        ("notice", "0003_category_notice_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="helpers.category",
            ),
        ),
    ]
