# Generated by Django 5.1.6 on 2025-02-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0004_alter_notice_category"),
        ("notification", "0004_alter_notification_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
