# Generated by Django 5.1.5 on 2025-01-31 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaroChatRooms",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaroChatContents",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tarot.tarochatrooms")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaroCardContents",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("card_id", models.IntegerField()),
                ("card_content", models.TextField()),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tarot.tarochatrooms")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
