# Generated by Django 5.1.6 on 2025-02-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tarot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tarochatrooms",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="tarochatcontents",
            name="room",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tarot.tarochatrooms"),
        ),
        migrations.AddField(
            model_name="tarocardcontents",
            name="room",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tarot.tarochatrooms"),
        ),
    ]
