# Generated by Django 5.1.6 on 2025-02-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarot", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarocardcontents",
            name="card_direction",
            field=models.CharField(choices=[("upright", "upright"), ("reversed", "reversed")], default="upright"),
            preserve_default=False,
        ),
    ]
