# Generated by Django 5.1.6 on 2025-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarot", "0003_tarocardcontents_card_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarocardcontents",
            name="card_id",
        ),
        migrations.AddField(
            model_name="tarocardcontents",
            name="card_name",
            field=models.CharField(default="empty"),
            preserve_default=False,
        ),
    ]
