# Generated by Django 5.1.5 on 2025-01-26 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nickname", models.CharField(max_length=30)),
                ("social_type", models.CharField(choices=[("KAKAO", "Kakao"), ("NAVER", "Naver")], max_length=10)),
                ("email", models.CharField(max_length=255)),
                ("gender", models.CharField(choices=[("male", "남성"), ("female", "여성")], max_length=10, null=True)),
                ("birth", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("SINGLE", "싱글"), ("DATING", "연애중"), ("MARRIED", "기혼")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("relationship_count", models.IntegerField(null=True)),
                ("marriage_count", models.IntegerField(null=True)),
                (
                    "marriage_values",
                    models.CharField(
                        choices=[("POSITIVE", "긍정적"), ("NEGATIVE", "부정적"), ("NEUTRAL", "중립적")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("job", models.CharField(max_length=20, null=True)),
                ("gender", models.CharField(choices=[("male", "남성"), ("female", "여성")], max_length=10, null=True)),
                ("age", models.IntegerField(null=True)),
                ("relationship_start", models.DateTimeField(null=True)),
                ("relationship_end", models.DateTimeField(null=True)),
                ("marriage_start", models.DateTimeField(null=True)),
                ("marriage_end", models.DateTimeField(null=True)),
                ("longest_relationship_period", models.DateTimeField(null=True)),
                ("emotional_state", models.CharField(max_length=30, null=True)),
                ("love_satisfaction", models.IntegerField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
        ),
    ]
