# Generated by Django 5.1.6 on 2025-02-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="user_id",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
