# Generated by Django 5.1.6 on 2025-02-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_heart_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
