# Generated by Django 5.1.5 on 2025-01-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="img_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="order",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="img_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
