# Generated by Django 5.1.5 on 2025-02-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_notice_img_url_alter_notice_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="img_url",
        ),
    ]
